version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: blacklist_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@db:5432/blacklist_db
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: blacklist_db
      DB_USER: postgres
      DB_PASSWORD: postgres123
      JWT_SECRET_KEY: "tu_clave_secreta_super_segura_aqui_cambiar_en_produccion"
      JWT_ALGORITHM: "HS256"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
